// buscar produtos
GET http://localhost:5005/produtos
 
 // criar produto
### 
POST  http://localhost:5005/produto
Content-Type: application/json

{
    "id": 234,
   "nome": "Produto 2",
   "preco": 350,
   "off": 17
}

###
// buscar produtos por id

GET http://localhost:5005/produtos/123